# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build filters
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Render all filters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install espeak ffmpeg -y
          python -m pip install --upgrade poetry
          poetry install
      - name: Build filters
        run: |
          poetry run ./filters/build.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Archive filters
        uses: actions/upload-artifact@v2
        with:
          name: "wraeblast-${{ env.RELEASE_NAME }}"
          path: |
            output/**
          retention-days: 5
        env:
          RELEASE_NAME: nightly-release-${{ steps.date.outputs.date }}
