# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build Python library
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install espeak ffmpeg -y
          python -m pip install --upgrade poetry
          poetry install
      - name: Test with pytest
        run: |
          poetry run pytest -vvv
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.repository_owner == 'darvid' && github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install poetry
        run: pip install poetry==1.1.6
      - uses: bjoluc/semantic-release-config-poetry@v1
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
